source 'https://github.com/CocoaPods/Specs.git'

target 'AdPieSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdPieSwiftSample
  pod 'AdPieSDK', '1.7.1'
  #pod 'Google-Mobile-Ads-SDK', '9.14.0'
  #pod 'AppLovinSDK', '11.6.1'

end